// Server
const PRODUCTION = 'PRODUCTION';
const DEVELOPMENT = 'DEVELOPMENT';
const TEST = 'test';

// Provider consts
const DATABASE_CONNECTION = 'DATABASE CONNECTION';
const USER_REPOSITORY = 'USER_REPOSITORY';

export { DATABASE_CONNECTION, USER_REPOSITORY, PRODUCTION, DEVELOPMENT, TEST };
